spring.application.name=aura-beauty-lounge

# Configurações de Conexão com o MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/aura_beauty_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=@381194mY@
api.security.token.secret=AuraBeautyLounge_Secret_123456

# Driver e Dialeto
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Hibernate - Cria as tabelas sozinho
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true